import type { Metadata } from 'next';
import Link from 'next/link';
import { Footer } from '@/components/layout/Footer';
import { LegalDocument } from '@/components/layout/LegalDocument';
import { Navbar } from '@/components/layout/Navbar';

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'The terms that govern access to and use of the InFaith Journey marketplace.',
};

const listClassName = 'list-disc space-y-2 pl-6 marker:text-secondary';

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-[#F7F3EE]">
      <Navbar />
      <LegalDocument
        eyebrow="Last updated: 1 October 2026"
        title="Terms & Conditions"
        introduction={
          <div className="space-y-4">
            <p>Welcome to InFaith Journey, accessible at infaithjourney.com (&quot;InFaith Journey&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot; or the &quot;Platform&quot;).</p>
            <p>InFaith Journey operates an online wedding and events marketplace designed to connect couples and other clients with wedding and event vendors, suppliers and service providers.</p>
            <p>These Terms govern your access to and use of the Platform, including any accounts, dashboards, artificial intelligence features, vendor listings and other services made available through InFaith Journey. By accessing the Platform, creating an account, joining as a Vendor, purchasing a subscription or otherwise using our services, you confirm that you have read, understood and agreed to these Terms. If you do not agree, you must not use the Platform.</p>
          </div>
        }
        sections={[
          { title: '1. Definitions', content: <div className="space-y-3"><p><strong>Client or Couple</strong> means any individual or organisation using InFaith Journey to search for, communicate with, enquire about or book Vendors.</p><p><strong>Vendor</strong> means any business, individual, company or service provider that advertises, lists or offers wedding or event-related products or services through InFaith Journey.</p><p><strong>User</strong> means any person accessing or using the Platform, including Clients and Vendors.</p><p><strong>Platform</strong> means the InFaith Journey website, dashboards, software, artificial intelligence tools and associated digital services.</p><p><strong>Vendor Services</strong> means products or services advertised or supplied by a Vendor independently of InFaith Journey.</p></div> },
          { title: '2. Eligibility and Account Registration', content: <div className="space-y-3"><p>You must be at least 18 years old and have the legal capacity to enter into binding agreements to create an account or transact through the Platform.</p><p>When creating an account, you agree to provide accurate, current and complete information and to keep it up to date. You are responsible for the confidentiality and security of your login credentials and all activity through your account.</p><p>Notify InFaith Journey as soon as reasonably possible if you believe your account has been accessed without authorisation. We may request additional verification where reasonably necessary for security, fraud prevention, platform integrity or legal compliance.</p></div> },
          { title: "3. InFaith Journey's Marketplace Role", content: <div className="space-y-3"><p>InFaith Journey provides a digital marketplace through which Clients can discover and communicate with independent wedding and event Vendors. Unless expressly stated otherwise, InFaith Journey is not the provider of the services advertised by Vendors.</p><p>Contracts for Vendor Services are generally concluded between the Client and the Vendor. Vendors determine their own prices, descriptions, availability, booking conditions, deposits, cancellation and refund policies, and delivery or performance obligations.</p><p>Enquiry, communication, booking or payment-related technology facilitates interactions between Users and does not, by itself, make InFaith Journey the supplier of the underlying Vendor Services. Nothing in these Terms excludes responsibility that we are legally required to accept.</p></div> },
          { title: '4. Vendor Selection and No Guarantee', content: <div className="space-y-3"><p>Although we aim to maintain a curated, high-quality marketplace, inclusion, verification or presentation of a Vendor is not a guarantee of that Vendor or its services. Users remain responsible for assessing suitability.</p><p>To the extent permitted by law, we do not guarantee:</p><ul className={listClassName}><li>quality, availability, pricing or service delivery;</li><li>suitability, safety or legality;</li><li>licensing, qualifications or punctuality;</li><li>the accuracy of Vendor representations; or</li><li>the outcome of any booking.</li></ul><p>Any screening or onboarding process is not a guarantee of future Vendor conduct or performance.</p></div> },
          { title: '5. Vendor Obligations', content: <div className="space-y-3"><p>Vendors must ensure their profiles are accurate and not misleading, including business details, prices, packages, photographs, descriptions, availability, qualifications, licences, portfolio material and service terms. Vendors must comply with all applicable laws, regulations, industry requirements and professional obligations.</p><p>A Vendor must not:</p><ul className={listClassName}><li>publish false or misleading information or impersonate another person or business;</li><li>upload content it has no right to use;</li><li>engage in fraudulent or unlawful activity or manipulate reviews;</li><li>compromise Platform security or misuse personal information;</li><li>harass Users or use the Platform in a way that could damage InFaith Journey or its Users.</li></ul><p>We may request that inaccurate or inappropriate content be corrected or removed.</p></div> },
          { title: '6. Vendor Content and Intellectual Property', content: <div className="space-y-3"><p>Vendors retain ownership of intellectual property they lawfully own in uploaded material. By submitting photographs, videos, logos, text, portfolio material or other content, a Vendor grants InFaith Journey a non-exclusive, worldwide, royalty-free licence to host, reproduce, resize, display, distribute and promote it for purposes connected with operating and marketing the Platform and the Vendor&apos;s listing.</p><p>This licence continues while the content is displayed or as reasonably necessary in previously created promotional material, subject to law. The Vendor warrants that it owns the content or has all necessary permissions and remains responsible for claims resulting from unauthorised content.</p></div> },
          { title: '7. InFaith Journey Intellectual Property', content: <div className="space-y-3"><p>Except for Vendor or User-generated content and third-party intellectual property, all intellectual property relating to InFaith Journey is owned by or licensed to InFaith Journey. This includes our name, branding, logos, Platform design, graphics, text, software, interfaces, databases, layout, icons, functionality and original content.</p><p>Without prior written permission, Users may not reproduce, republish, distribute, scrape, systematically extract, reverse engineer, modify, sell, commercially exploit or create derivative works from our intellectual property, except where permitted by law.</p></div> },
          { title: '8. Artificial Intelligence Features', content: <div className="space-y-3"><p>We may provide AI-powered features, including an AI concierge or digital planning assistant. AI-generated information assists Users with discovering Vendors, planning events and navigating the Platform, but may be incomplete, outdated or inaccurate.</p><p>Users should independently confirm important details—including pricing, availability, dates, venue information, packages, contractual conditions and booking requirements—with the relevant Vendor before making a decision or payment. AI recommendations are not a guarantee, professional advice or endorsement.</p></div> },
          { title: '9. Vendor Subscriptions and Platform Fees', content: <div className="space-y-3"><p>Certain Vendor features may require a paid subscription or Platform fee. The price, billing frequency, period, features, applicable taxes and payment conditions will be displayed before purchase or activation.</p><p>By purchasing a recurring subscription, the Vendor authorises the payment provider to process recurring charges according to the selected billing cycle until cancellation or termination. Statutory consumer rights continue to apply, and mandatory South African cancellation rights prevail over inconsistent terms.</p></div> },
          { title: '10. Refunds and Cancellations of InFaith Journey Fees', content: <div className="space-y-3"><p>Except where required by law, provided in the selected subscription plan or agreed by us in writing, fees already earned for access or subscription services are not ordinarily refundable. Any legally permitted cancellation charge will be reasonable and subject to consumer protection legislation.</p><p>Cancelling a Vendor subscription does not necessarily cancel or affect agreements already entered into between that Vendor and Clients.</p></div> },
          { title: '11. Vendor Bookings, Deposits and Refunds', content: <div className="space-y-3"><p>Unless expressly stated otherwise, each Vendor is responsible for its own booking, deposit, postponement, rescheduling, cancellation and refund policies. Clients should review and agree to the relevant Vendor&apos;s terms before booking.</p><p>Disputes about Vendor Services should ordinarily first be addressed directly between the Client and Vendor. We may assist communications at our discretion, but are not required to adjudicate contractual disputes between Users. This does not affect legal rights against InFaith Journey itself.</p></div> },
          { title: '12. Payments and Third-Party Payment Providers', content: <div className="space-y-3"><p>We may use independent payment providers to process Platform fees, subscriptions or other permitted transactions. Payment information may be processed under that provider&apos;s terms and privacy practices, and we do not guarantee uninterrupted availability of third-party payment systems.</p><p>Users are responsible for submitting accurate payment information and being authorised to use the selected payment method.</p></div> },
          { title: '13. Reviews, Ratings and User Content', content: <div className="space-y-3"><p>Reviews, ratings, photographs, comments and other User content must be truthful, lawful and based on genuine experiences. Users must not submit fraudulent reviews, defamatory, threatening, abusive, unlawful or discriminatory material, spam, another person&apos;s confidential information, or content that infringes intellectual property.</p><p>We may moderate, restrict or remove content that violates these Terms or applicable law.</p></div> },
          { title: '14. Privacy and Protection of Personal Information', content: <div className="space-y-3"><p>We process personal information in accordance with applicable data protection laws, including the Protection of Personal Information Act 4 of 2013 (POPIA), where applicable. Our <Link href="/privacy-policy" className="font-semibold text-primary underline decoration-secondary/60 underline-offset-4">Privacy Policy</Link> explains the information collected, why it is processed, how it is protected and shared, and Users&apos; rights.</p><p>Users acknowledge that personal information may be processed as reasonably necessary to operate and secure the Platform, provide requested services and fulfil lawful business and regulatory requirements.</p></div> },
          { title: '15. Third-Party Websites and Services', content: <p>The Platform may link to Vendor websites, social media, payment providers and other third-party services. We do not control these services and are not responsible for their content, security, availability, products, services or privacy practices. Users should review the applicable third-party terms and privacy policies.</p> },
          { title: '16. Platform Availability', content: <div className="space-y-3"><p>We aim to maintain reliable access but do not guarantee uninterrupted or error-free operation. The Platform may be unavailable due to maintenance, upgrades, technical issues, cybersecurity measures, third-party interruptions or circumstances reasonably outside our control.</p><p>We may modify, update or discontinue functionality where reasonably necessary.</p></div> },
          { title: '17. Suspension and Termination', content: <div className="space-y-3"><p>We may suspend, restrict or terminate an account where we reasonably believe a User has materially breached these Terms, acted fraudulently or unlawfully, created a security risk, repeatedly provided misleading information, infringed intellectual property, abused another User or could materially harm the Platform or Users.</p><p>Where reasonably appropriate, we may offer an opportunity to address the issue. We may act immediately when necessary to protect Users, comply with law, prevent fraud or address a serious security risk.</p></div> },
          { title: '18. Limitation of Liability', content: <div className="space-y-3"><p className="font-bold text-foreground/90">Important: this section limits certain liabilities and should be read carefully.</p><p>To the fullest extent permitted by law, InFaith Journey will not be liable for loss or damage arising solely from the independent acts, omissions, representations or performance of a Vendor or another User, or for indirect or consequential loss where such liability may lawfully be excluded.</p><p>Nothing in these Terms excludes liability that cannot legally be excluded, waives statutory consumer rights, excludes responsibility imposed on us by law, or limits liability where unlawful, unfair or unenforceable. Independent Vendors remain responsible for Vendor Services contracted directly with them.</p></div> },
          { title: '19. Indemnity', content: <p>To the extent permitted by law, a User or Vendor may be responsible for losses, claims or reasonable costs suffered by InFaith Journey resulting directly from that User&apos;s unlawful Platform use, infringement of third-party intellectual property, fraudulent conduct, unauthorised uploaded content or material breach of these Terms. This does not require a consumer to waive a statutory right that cannot legally be waived.</p> },
          { title: '20. Complaints', content: <div className="space-y-3"><p>Users with a Platform-related problem should contact us using the details below. Complaints concerning independent Vendor Services should ordinarily first be raised with the relevant Vendor.</p><p>This process does not remove a consumer&apos;s right to approach an appropriate regulator, ombud, tribunal or court.</p></div> },
          { title: '21. Governing Law', content: <p>These Terms are governed by the laws of the Republic of South Africa. Subject to mandatory consumer rights concerning jurisdiction or dispute resolution, disputes will be dealt with by courts or other competent dispute-resolution bodies with jurisdiction in South Africa.</p> },
          { title: '22. Changes to These Terms', content: <div className="space-y-3"><p>We may update these Terms to reflect Platform changes, new functionality, business operations, security requirements or applicable law. The latest version and updated date will be published on the Platform.</p><p>Where a change materially affects existing paid services or Users&apos; rights, reasonable notice will be provided where required. Continued use after updated Terms take effect constitutes acceptance to the extent permitted by law.</p></div> },
          { title: '23. Severability', content: <p>If a provision is found unlawful or unenforceable, it will be interpreted or limited to the minimum extent necessary to make it enforceable where possible. Remaining provisions continue in effect.</p> },
          { title: '24. Entire Agreement', content: <p>These Terms, together with our Privacy Policy, applicable Vendor subscription terms and policies expressly incorporated into them, govern use of the Platform. Separate contracts between Clients and Vendors remain agreements between those parties.</p> },
          { title: '25. Electronic Communications', content: <p>Users agree that communications relating to their accounts, subscriptions and Platform use may be provided electronically, including by email, Platform notification or other electronic means permitted by law.</p> },
          { title: '26. Business Information', content: <div className="overflow-hidden rounded-2xl border border-primary/10 bg-white/45"><dl className="divide-y divide-primary/10"><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Trading name</dt><dd className="sm:col-span-2">InFaith Journey</dd></div><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Country</dt><dd className="sm:col-span-2">Republic of South Africa</dd></div><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Location</dt><dd className="sm:col-span-2">Cape Town, South Africa</dd></div><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Telephone</dt><dd className="sm:col-span-2"><a href="tel:+27784420278" className="text-primary hover:underline">+27 78 442 0278</a></dd></div><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Website</dt><dd className="sm:col-span-2"><a href="https://infaithjourney.com" className="text-primary hover:underline">infaithjourney.com</a></dd></div><div className="grid gap-1 p-4 sm:grid-cols-3"><dt className="font-semibold">Email</dt><dd className="sm:col-span-2"><a href="mailto:admin@infaithjourney.com" className="text-primary hover:underline">admin@infaithjourney.com</a></dd></div></dl></div> },
          { title: '27. Contact Us', content: <div className="space-y-2"><p>Questions about these Terms may be directed to:</p><address className="not-italic"><strong>InFaith Journey</strong><br /><a href="https://infaithjourney.com" className="text-primary hover:underline">infaithjourney.com</a><br /><a href="mailto:admin@infaithjourney.com" className="text-primary hover:underline">admin@infaithjourney.com</a></address></div> },
        ]}
      />
      <Footer />
    </div>
  );
}
